# Generated by Django 5.2.5 on 2025-09-24 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='The author who wrote this book. Deleting the author will also delete their books.', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author'),
        ),
    ]
